name = "BandedMats"
uuid = "1effaa55-788a-4a47-91fb-d4bdff55c3e7"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.0"

[deps]

[weakdeps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "Symbolics", "LinearAlgebra"]

[compat]
julia = "1.9"
